name = "ROCAnalysis"
uuid = "f535d66d-59bb-5153-8d2b-ef0a426c6aff"
repo = "https://github.com/davidavdav/ROCAnalysis.jl.git"
version = "0.3.2"

[compat]
julia = "1"
RecipesBase = "1"
SpecialFunctions = "1"
DataFrames = "0.20", "0.21", "0.22"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecZlib = "944b1d66-785c-5afd-91f1-9de20f533193"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CSV", "Mmap", "CodecZlib"]
