name = "ROCAnalysis"
repo = "https://github.com/davidavdav/ROCAnalysis.jl.git"
uuid = "f535d66d-59bb-5153-8d2b-ef0a426c6aff"
version = "0.3.0-DEV"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"


[extras]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CSV", "GZip", "Test"]
